name: Détecteur de Bonnes Affaires de Voitures

on:
  schedule:
    # S'exécute toutes les heures. Ajustez au besoin (ex: '0,30 * * * *' toutes les 30 min)
    - cron: '0 * * * *'
  workflow_dispatch: # Permet le déclenchement manuel depuis l'onglet GitHub Actions

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le code
      uses: actions/checkout@v4

    - name: Configurer Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Ou plus récent, ex: '3.10', '3.11'

    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Exécuter le bot
      env:
        MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python main.py

    - name: Commiter et pousser annonces_vues.json mis à jour
      uses: EndBug/add-and-commit@v9
      with:
        add: 'data/annonces_vues.json'
        message: 'Bot: Mise à jour des données d''annonces vues'
        committer_name: 'GitHub Actions Bot'
        committer_email: 'actions@github.com'
      # Ne commiter que s'il y a eu des changements et pas sur les pull requests
      if: success() && github.ref == 'refs/heads/main' # ou votre branche par défaut
